### ISSUE TITLE
No executable found

### ISSUE THREAD

**Issue by redex589** [NovoG93/sjtu-drone#20]
i tried to run the script using the command:
'ros2 run sjtu_drone_control drone_position_control.py'
it return a No executable found error
i double check the setup.py and package they all seem find

**Comment by NovoG93** [comment]
The executeable is named `drone_position_control` not `drone_position_control.py`.
So the following should work:

```
ros2 run sjtu_drone_control drone_position_control
```

**Comment by redex589** [comment]
i'm just started learning ROS apology for all the dumb question 

it gave me this error:
Traceback (most recent call last):
  File "/home/ros2/uav_ws/install/sjtu_drone_control/lib/sjtu_drone_control/drone_position_control", line 33, in <module>
    sys.exit(load_entry_point('sjtu-drone-control==0.0.0', 'console_scripts', 'drone_position_control')())
  File "/home/ros2/uav_ws/install/sjtu_drone_control/lib/sjtu_drone_control/drone_position_control", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ros2/uav_ws/install/sjtu_drone_control/lib/python3.10/site-packages/sjtu_drone_control/drone_position_control.py", line 3, in <module>
    from drone_utils.drone_object import DroneObject
ModuleNotFoundError: No module named 'drone_utils'
[ros2run]: Process exited with failure 1

**Comment by PranayG** [comment]
@NovoG93 I have encountered the same error. Will you be able to share the work around for the same ?
